# Generated by Django 2.0.6 on 2019-06-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('card_id', models.CharField(max_length=255, verbose_name='优惠券id')),
                ('title', models.CharField(max_length=255, verbose_name='优惠券标题')),
                ('describe', models.CharField(max_length=255, verbose_name='优惠券描述')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='优惠金额')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='使用金额要求')),
                ('card_count', models.IntegerField(verbose_name='优惠券数量')),
                ('get_count', models.IntegerField(default=1, verbose_name='用户领取数量')),
                ('validity', models.DateTimeField(verbose_name='有效期')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
                'db_table': 'gd_card',
            },
        ),
    ]
