# Generated by Django 2.0.6 on 2019-07-31 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='wx_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.WxUser', verbose_name='微信用户'),
        ),
    ]
