# Generated by Django 2.0.6 on 2019-06-24 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('is_use', models.BooleanField(default=False, verbose_name='是否使用')),
                ('card_token', models.CharField(max_length=255, verbose_name='优惠券token')),
            ],
            options={
                'verbose_name': '用户优惠券',
                'verbose_name_plural': '用户优惠券',
                'db_table': 'gd_user_card',
            },
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_id',
        ),
        migrations.AlterField(
            model_name='card',
            name='validity',
            field=models.DateField(verbose_name='有效期'),
        ),
        migrations.AddField(
            model_name='usercard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Card', verbose_name='所属优惠券id'),
        ),
        migrations.AddField(
            model_name='usercard',
            name='wx_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.WxUser', verbose_name='微信用户'),
        ),
    ]
