# Generated by Django 2.0.6 on 2019-04-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexcarousel',
            name='image',
            field=models.ImageField(blank=True, upload_to='banner', verbose_name='轮播图片'),
        ),
    ]
