# Generated by Django 2.0.6 on 2019-04-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='是否主推'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='show_region',
            field=models.SmallIntegerField(choices=[(0, '产品大图'), (1, '产品图文')], verbose_name='展示区域'),
        ),
    ]
