# Generated by Django 2.0.6 on 2019-06-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='name',
            field=models.CharField(default='商品未命名', max_length=255, verbose_name='商品名称'),
        ),
    ]
