# Generated by Django 2.0.6 on 2019-06-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='商品销量'),
        ),
    ]
