# Generated by Django 2.0.6 on 2019-04-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190427_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='classify',
            new_name='classify_id',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='sort',
            new_name='sort_id',
        ),
    ]
