# Generated by Django 2.0.6 on 2019-04-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190419_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexVideoOrBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('image', models.ImageField(blank=True, upload_to='banner', verbose_name='图片')),
                ('video', models.FileField(blank=True, upload_to='video', verbose_name='视频')),
                ('show_type', models.SmallIntegerField(choices=[(0, '图片'), (1, '视频')], default=0, verbose_name='展示类型')),
                ('url', models.CharField(blank=True, max_length=256, verbose_name='跳转地址')),
            ],
            options={
                'verbose_name': '首页视频or图片',
                'verbose_name_plural': '首页视频or图片',
                'db_table': 'gd_index_video_or_banner',
            },
        ),
    ]
