# Generated by Django 2.0.6 on 2019-07-16 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_commoditybanner'),
    ]

