# Generated by Django 2.0.6 on 2019-04-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190428_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='classify_id',
            new_name='classify',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='sort_id',
            new_name='sort',
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='GoodsImg', verbose_name='图片'),
        ),
    ]
