# Generated by Django 2.0.6 on 2019-04-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190429_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='goods_id',
            new_name='goods',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='goods_id',
            new_name='goods',
        ),
        migrations.RenameField(
            model_name='goodsimage',
            old_name='goods_id',
            new_name='goods',
        ),
    ]
