# Generated by Django 2.0.6 on 2019-07-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('image', models.ImageField(blank=True, upload_to='UserBackgroundImg', verbose_name='背景图片')),
            ],
            options={
                'verbose_name': '用户页面背景图',
                'verbose_name_plural': '用户页面背景图',
                'db_table': 'gd_user_background',
            },
        ),
    ]
