# Generated by Django 2.0.6 on 2019-06-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_code',
            field=models.CharField(default='', max_length=10, verbose_name='邮编号'),
        ),
    ]
