# Generated by Django 2.0.6 on 2019-06-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxuser',
            name='birthday',
            field=models.CharField(default='', max_length=30, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='head_portrait',
            field=models.CharField(default='未上传头像', max_length=255, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='height',
            field=models.CharField(default='', max_length=10, verbose_name='身高'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='nick_name',
            field=models.CharField(default='未命名用户', max_length=30, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='weight',
            field=models.CharField(default='', max_length=10, verbose_name='体重'),
        ),
    ]
