# Generated by Django 2.0.6 on 2019-05-09 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190508_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('addressee', models.CharField(max_length=30, verbose_name='收件人')),
                ('phone', models.IntegerField(max_length=11, null=True, verbose_name='联系人电话')),
                ('shipping_address', models.CharField(max_length=255, verbose_name='收件地址')),
                ('is_default', models.BooleanField(default=0, verbose_name='是否默认')),
            ],
            options={
                'verbose_name': '收货地址信息',
                'verbose_name_plural': '收货地址信息',
            },
        ),
        migrations.CreateModel(
            name='VipLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('level', models.CharField(max_length=20, verbose_name='等级名称')),
                ('minmum_integral', models.IntegerField(max_length=10, verbose_name='积分要求值')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='head_portrait',
            field=models.URLField(blank=True, verbose_name='用户头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='integral',
            field=models.IntegerField(default=0, max_length=20, verbose_name='会员积分'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(max_length=11, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(max_length=50, verbose_name='用户openid'),
        ),
        migrations.AddField(
            model_name='address',
            name='openid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户openid'),
        ),
    ]
