# Generated by Django 2.0.6 on 2019-06-05 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_address_address_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='openid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.WxUser', verbose_name='用户openid'),
        ),
    ]
