# Generated by Django 2.0.6 on 2019-06-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190605_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='openid',
            field=models.CharField(max_length=255, verbose_name='用户openid'),
        ),
    ]
