# Generated by Django 2.0.6 on 2019-07-31 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('goods', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxorder',
            name='wx_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.WxUser', verbose_name='微信用户'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Commodity', verbose_name='所属商品'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='order_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderInfo', verbose_name='订单号'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='wx_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.WxUser', verbose_name='微信用户'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='wx_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.WxUser', verbose_name='微信用户'),
        ),
    ]
