# Generated by Django 2.0.6 on 2019-06-16 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('goods', '0002_commodity_sales'),
        ('order', '0002_orderinfo_wx_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('commodity_name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('commodity_specifications', models.CharField(max_length=255, verbose_name='商品规格')),
                ('commodity_price', models.FloatField(verbose_name='商品单价')),
                ('commodity_count', models.IntegerField(verbose_name='商品数量')),
                ('commodity_image', models.CharField(max_length=255, verbose_name='商品图片')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Commodity', verbose_name='所属商品')),
                ('order_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderInfo', verbose_name='订单号')),
                ('wx_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.WxUser', verbose_name='微信用户')),
            ],
            options={
                'verbose_name': '订单清单表',
                'verbose_name_plural': '订单清单表',
                'db_table': 'gd_order_list',
            },
        ),
    ]
