# Generated by Django 2.0.6 on 2019-08-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190731_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='cancel_time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='取消时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='complete_time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='courier_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='快递单号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='returns_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='退货单号'),
        ),
    ]
