# Generated by Django 2.0.6 on 2019-06-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190615_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='收件人姓名'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='收件人手机'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='收件地址'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='cancel_time',
            field=models.CharField(max_length=30, null=True, verbose_name='取消时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='complete_time',
            field=models.CharField(max_length=30, null=True, verbose_name='完成时间'),
        ),
    ]
