# Generated by Django 2.0.6 on 2019-06-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderinfo_wx_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order_count',
            new_name='total_count',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order_total_price',
            new_name='total_price',
        ),
    ]
