# Generated by Django 2.0.6 on 2019-06-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('order', '0003_orderlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('wx_order', models.CharField(max_length=255, verbose_name='微信支付订单号')),
                ('pay_time', models.CharField(max_length=30, null=True, verbose_name='支付完成时间')),
                ('order_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderInfo', verbose_name='订单号')),
                ('wx_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.WxUser', verbose_name='微信用户')),
            ],
            options={
                'verbose_name': '微信支付订单',
                'verbose_name_plural': '微信支付订单',
                'db_table': 'gd_wx_order',
            },
        ),
    ]
