# Generated by Django 2.0.6 on 2019-06-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_wxorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='note',
            field=models.CharField(default='', max_length=255, verbose_name='备注'),
        ),
    ]
