# Generated by Django 2.0.6 on 2019-06-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderinfo_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='returns_number',
            field=models.CharField(default='', max_length=255, verbose_name='退货单号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='courier_number',
            field=models.CharField(default='', max_length=255, verbose_name='快递单号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '待发货'), (3, '已发货'), (4, '已完成'), (5, '待退款'), (6, '已关闭')], default=0, verbose_name='订单状态'),
        ),
    ]
