# Generated by Django 2.0.6 on 2019-06-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190620_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='discount_price',
            field=models.FloatField(default=0, verbose_name='优惠金额'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '待发货'), (3, '已发货'), (4, '已完成'), (5, '待退款'), (6, '已关闭'), (7, '退款成功')], default=0, verbose_name='订单状态'),
        ),
    ]
